Feature/forms
mpdocs/mpdocs-frontend pull request #1
Opened 2024-03-06 21:01 UTC by dangannn

trash

2024-03-07 19:40 UTC, Yakser requested changes

2024-03-07 19:40 UTC, Yakser commented on src/app/auth/page.tsx
> +'use client'
тут можно убрать 'use client', нет ведь никаких взаимодействий с клиентом

2024-03-07 19:40 UTC, Yakser commented on src/app/layout.tsx
> +'use client'
давай сделаем компонент Providers с use client и в него положим всех провайдеров, а отсюда use client надо убрать. Я вообще где то слышал что layout всегда серверный должен быть)

2024-03-07 19:40 UTC, Yakser commented on src/app/reports/page.tsx
> +'use client';
тоже не надо тут)

2024-03-08 12:59 UTC, dangannn commented on src/app/layout.tsx
> +'use client'
убрал

2024-03-08 12:59 UTC, dangannn commented on src/app/reports/page.tsx
> +'use client';
поправил

2024-04-28 14:12 UTC, Yakser requested changes
все круто, но нужно лейблы вынести в отдельный компонент, тк дублируется много чего и еще по мелочи отписал

2024-04-28 14:12 UTC, Yakser commented on src/app/components/ReportsForm/index.tsx
> +
линтер бы подрубить, две пустые строкии вроде не ок

2024-04-28 14:12 UTC, Yakser commented on src/app/components/ReportsForm/index.tsx
> +type ReportsData = {
мб переменуем Reports -> Report? форма к одному отчету относится, имхо логичнее в единственном числе назвать

2024-04-28 14:12 UTC, Yakser commented on src/app/components/ReportsForm/index.tsx
> +let qualificationImprovementExample: ReportsData = {
а почему Example?

2024-04-28 14:12 UTC, Yakser commented on src/app/components/ReportsForm/index.tsx
> +let qualificationImprovementExample: ReportsData = {
это же тайтлы

2024-04-28 14:12 UTC, Yakser commented on src/app/components/ReportsForm/index.tsx
> +                <legend>{Object.keys(qualificationImprovementExample)[0]}</legend>
как будто 0 смысла выносить лейблы в какой то объект (по крайней мере таким способом)

в теории можно каждой надписи задать какой-то ключ и хранить все в одном объекте (потом удобно будет перевод на другие языки делать, но нам такое не надо, поэтому пофиг))

2024-04-28 14:12 UTC, Yakser commented on src/app/components/ReportsForm/index.tsx
> +                    htmlFor={`qualification_improvement.form`} key={`qualification_improvement.form`}>
ты все равно тут указываешь конкретный класс

никаких плюсов не вижу выносить лейблы, давай сюда их вернем и вынесем в компонент все что в label лежит (с самим тегом label), так сможем избежать дублирования классов и стилей в будущем

2024-04-28 14:12 UTC, Yakser commented on src/app/components/ReportsForm/index.tsx
> +                disabled={!isValid}
сюда потом ` || isLoading` пихнем

2024-04-28 14:12 UTC, Yakser commented on src/app/components/ReportsForm/index.tsx
> +                    htmlFor={`qualification_improvement.country`} key={`qualification_improvement.country`}>
имя страны точно должно быть textarea?

2024-04-28 14:12 UTC, Yakser commented on src/app/components/ReportsForm/index.tsx
> +                    htmlFor={`qualification_improvement.diploma_date`} key={`qualification_improvement.diploma_date`}>
ну тут судя по названию точно не textarea нужно

2024-04-28 14:12 UTC, Yakser commented on src/app/components/ReportsForm/index.tsx
> +                    <textarea
и тут

2024-04-28 14:12 UTC, Yakser commented on src/app/components/ReportsForm/index.tsx
> +                            htmlFor={`methodical_works.${index}.name`} key={`methodical_works.${index}.name`}>
крч нужно подобрать всем инпутам подходящие типы

2024-04-28 14:12 UTC, Yakser commented on src/app/components/AuthForm/index.tsx
> +                        required: "обязаьедб",
каво 
<img width="176" alt="image" src="https://github.com/mpdocs/mpdocs-frontend/assets/53031664/f80ba871-7338-4887-adb1-9d2e32293f5f">

2024-05-01 10:50 UTC, Yakser approved these changes
какой пиздец
я шипаю

2024-05-01 10:50 UTC, merged