Feature/antd
mpdocs/mpdocs-frontend pull request #3
Opened 2024-05-02 08:18 UTC by Alexanderbr1

2024-05-11 12:54 UTC, Yakser commented on src/app/components/Navbar/LeftMenu.tsx
> +        <Link href="/reports">Reports</Link>
и тут

2024-05-11 12:55 UTC, Yakser commented on src/app/auth/isAuth.tsx
> +      if (!user.id) {
user не может быть undefined?

2024-05-11 12:55 UTC, Yakser commented on src/app/auth/isAuth.tsx
> +    if (!user.id) {
и тут

2024-05-11 12:57 UTC, Yakser commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", "postcss.config.js"],
postcss?... нахуя а главное зачем. давай это уберем и еще удалим конфиги тэилвинда
и уберем его нахуй из зависимостей

2024-05-11 12:58 UTC, Yakser commented on src/app/globals.css
> -@tailwind base;
-> scss

2024-05-11 12:58 UTC, Yakser commented on src/app/layout.tsx
> +            <Navbar></Navbar>
`<Navbar/>`

2024-05-11 13:04 UTC, Yakser commented on src/app/globals.css
> -@tailwind base;
сам файл в смысле  давай сделаем scss

2024-05-11 13:04 UTC, Yakser commented on src/app/auth/isAuth.tsx
> +export default function isAuth(Component: any) {
надо тип нормальный 
либо unknown

2024-05-19 13:56 UTC, Yakser requested changes

2024-05-19 13:56 UTC, Yakser commented on src/app/components/Navbar/styles.module.scss
> +.navbar {
index.module.scss

2024-05-19 13:56 UTC, Yakser commented on src/app/components/ReportForm/styles.module.scss
> +//.form {
давай удалим файл

2024-05-19 14:00 UTC, Yakser requested changes

2024-05-19 14:00 UTC, Yakser commented on src/app/components/AuthForm/styles.module.scss
> +.form {
index.module.scss обычно именуют

2024-05-19 14:03 UTC, Yakser requested changes

2024-05-19 14:03 UTC, Yakser commented on src/app/components/AuthForm/index.tsx
> +    if (token) {
можно сразу `if (getAccessToken())` без ненужной переменной

2024-05-19 14:04 UTC, Yakser requested changes

2024-05-19 14:04 UTC, Yakser commented on src/app/auth/isAuth.tsx
> +import { redirect } from "next/navigation";
давай заменим на router.push

2024-05-19 14:13 UTC, dangannn commented on src/app/auth/isAuth.tsx
> +import { redirect } from "next/navigation";
заменил

2024-05-19 14:13 UTC, dangannn commented on src/app/components/AuthForm/index.tsx
> +    if (token) {
заменил

2024-05-19 14:13 UTC, dangannn commented on src/app/components/AuthForm/styles.module.scss
> +.form {
удалил

2024-05-19 14:14 UTC, dangannn commented on src/app/components/AuthForm/styles.module.scss
> +.form {
переименовал*

2024-05-19 14:14 UTC, dangannn commented on src/app/components/ReportForm/styles.module.scss
> +//.form {
удалил

2024-05-19 14:18 UTC, Yakser commented on src/app/components/Navbar/index.module.scss
> +.navbar__menu .leftMenu {
это ж scss почему не заюзаешь вложенность?

2024-05-19 14:18 UTC, Yakser commented on src/app/components/Navbar/index.module.scss
> +.navbar__menu .ant-menu-item {
тут

2024-05-19 14:18 UTC, Yakser commented on src/app/components/Navbar/index.module.scss
> +.navbar__menu .ant-menu-horizontal {
тут

2024-05-19 14:18 UTC, Yakser commented on src/app/components/Navbar/index.module.scss
> +.navbar__menu .ant-layout-header {
тут

2024-05-19 14:18 UTC, Yakser commented on src/app/components/Navbar/index.module.scss
> +.navbar__menu .rightMenu {
тут

2024-05-19 14:19 UTC, Yakser approved these changes
@Alexanderbr1 фиксани потом scss файлики, сделай красиво) а так все норм

2024-05-19 14:19 UTC, merged