fix: navbar
mpdocs/mpdocs-frontend pull request #6
Opened 2024-05-19 18:53 UTC by dangannn

2024-05-19 19:25 UTC, Yakser requested changes

2024-05-19 19:25 UTC, Yakser commented on src/app/components/Navbar/LeftMenu.tsx
> +        <h3 className={styles.brand_font}>Отчеты</h3>
почему h3?

2024-05-19 19:25 UTC, Yakser commented on src/app/components/Navbar/LeftMenu.tsx
> +        <h3 className={styles.brand_font}>Отчеты</h3>
ты попытался из логотипа сделать пункт меню зачем-то, убери его вообще из меню и сделай просто спаном или параграфом. это точно не заголовок и тем более не пункт меню

2024-05-19 19:25 UTC, Yakser commented on src/app/components/Navbar/LeftMenu.tsx
> +        <h3 className={styles.brand_font}>Отчеты</h3>
пусть слева будет лого в центре менюшка эта а справа user card какой нибудь

2024-05-19 19:25 UTC, Yakser commented on src/app/components/Navbar/LeftMenu.tsx
> +    key: "report_form",
ключи давай унесем в enum в файлик types.ts в папке компонента например

2024-05-19 19:25 UTC, Yakser commented on src/app/components/Navbar/LeftMenu.tsx
> +    key: "report_form",
и тогда уж не report_form, а create_report
хз на че эти ключи влияют но это не оч подходящее название

2024-05-19 19:26 UTC, Yakser requested changes

2024-05-19 19:26 UTC, Yakser commented on src/app/components/Navbar/index.module.scss
> +  .brand_font {
странное имя класса

2024-05-20 14:10 UTC, dangannn commented on src/app/components/Navbar/LeftMenu.tsx
> +    key: "report_form",
они здесь в единственном месте используются, точно есть смысл выносить?

2024-05-20 14:10 UTC, dangannn commented on src/app/components/Navbar/LeftMenu.tsx
> +        <h3 className={styles.brand_font}>Отчеты</h3>
заменил на span

2024-05-20 14:11 UTC, dangannn commented on src/app/components/Navbar/LeftMenu.tsx
> +    key: "report_form",
поправил

2024-05-20 14:12 UTC, dangannn commented on src/app/components/Navbar/index.module.scss
> +  .brand_font {
порефакторил файлик

2024-05-21 19:48 UTC, Yakser commented on src/app/components/Navbar/LeftMenu.tsx
> +    key: "report_form",
хм, действительно. тогда давай оставим так

2024-05-21 19:50 UTC, Yakser requested changes

2024-05-21 19:50 UTC, Yakser commented on src/app/components/Navbar/RightMenu.tsx
> +          <Link href="/profile">{`${user.first_name} ${user.last_name} `}</Link>
пробел лишний после last_name

2024-05-21 19:52 UTC, Yakser requested changes

2024-05-21 19:52 UTC, Yakser commented on src/app/components/Navbar/LeftMenu.tsx
> +        <span className={styles.header__logo}>Отчеты</span>
Тексты бы кнш нормальные сделать

2024-05-21 19:52 UTC, Yakser commented on src/app/components/Navbar/LeftMenu.tsx
> +    label: <Link href="/reports">Создать отчет</Link>,
Везде слово отчет отчет отчет, надо придумать как сделать лучше, не в этом ПРе уже думаю но точно надо

2024-05-21 19:52 UTC, Yakser commented on src/app/components/Navbar/LeftMenu.tsx
> +    label: <Link href="/reports">Создать отчет</Link>,
мб просто Отчёты и две иконки: плюсик и глазик, пока нет особо идей

2024-05-21 19:56 UTC, Yakser requested changes

2024-05-21 19:56 UTC, Yakser commented on src/app/components/Navbar/index.tsx
> +          <h3 className={styles.header__logo_mobile}>Отчеты</h3>
не заменил на span

2024-05-21 19:59 UTC, Yakser commented
надо фиксануть страничку 404, поменять тему на светлую а то там текст не видно

2024-05-21 20:00 UTC, Yakser commented
почему-то перезагружается страница если неатворизованный заходу на страничку списка отчетов

2024-05-22 18:22 UTC, dangannn commented on src/app/components/Navbar/index.tsx
> +          <h3 className={styles.header__logo_mobile}>Отчеты</h3>
заменил

2024-05-22 18:22 UTC, dangannn commented on src/app/components/Navbar/LeftMenu.tsx
> +    label: <Link href="/reports">Создать отчет</Link>,
убрал слово отчеты

2024-05-22 18:22 UTC, dangannn commented on src/app/components/Navbar/LeftMenu.tsx
> +        <span className={styles.header__logo}>Отчеты</span>
убрал

2024-05-22 18:23 UTC, dangannn commented on src/app/components/Navbar/RightMenu.tsx
> +          <Link href="/profile">{`${user.first_name} ${user.last_name} `}</Link>
поправил

2024-05-23 11:56 UTC, Yakser approved these changes
классно сделано, заебись

2024-05-24 10:22 UTC, merged