feat: add styles for inputs and change types for some inputs
mpdocs/mpdocs-frontend pull request #7
Opened 2024-05-24 18:29 UTC by xAksssenov

Добавление стилей

2024-05-24 18:38 UTC, Yakser requested changes
ребейзнись на мейн

2024-06-02 09:30 UTC, Alexanderbr1 commented on src/app/components/ReportForm/index.module.scss
> +    outline: none;
у button и buttonDelete много одинковых стилей, может быть так?

```
. button {
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 1rem;
    border: none;
    outline: none;
    width: 18.75rem;
    margin: 0 auto;
    
    &-delete {
       width: 12.5rem;
       margin-bottom: 1rem;
    }
}

2024-06-02 18:02 UTC, Alexanderbr1 commented on src/app/components/ReportForm/index.tsx
> +                  className={`${styles["button-delete"]}`}
почему везде через точку,  а тут так?

2024-06-02 19:48 UTC, Yakser requested changes

2024-06-02 19:48 UTC, Yakser commented on src/app/components/ReportForm/index.tsx
> +            placeholder: "Номер вашего диплома",
Давай какое то валидное значение напишем

2024-06-02 19:48 UTC, Yakser commented on src/app/components/ReportForm/index.tsx
> +                  className={`${styles["button-delete"]}`}
Потому что тут через дефис имя класса написано. Хз зачем самому себе трудности создавать, давац переименуем в deleteButton

2024-06-02 19:59 UTC, Alexanderbr1 commented on src/app/components/ReportForm/index.tsx
> +                  className={`${styles["button-delete"]}`}
исправил

2024-06-17 20:41 UTC, Yakser approved these changes
красавчик

2024-06-17 20:41 UTC, merged